sudo: required
services:
  - docker

before_install:
  - docker build -t atdinhnhan/docker-react -f ./client/Dockerfile.dev ./client

scripts:
  - docker run -e CI=true atdinhnhan/docker-react npm test -- --coverage

after_success:
  - docker build -t atdinhnhan/multi-client ./client
  - docker build -t atdinhnhan/multi-nginx ./nginx
  - docker build -t atdinhnhan/multi-server ./server
  - docker build -t atdinhnhan/multi-worker ./worker
  # Login Docker
  - docker logout
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" -p "$DOCKER_PASSWORD" docker.io
  # Take those images and push them to docker hub
  - docker push atdinhnhan/multi-client
  - docker push atdinhnhan/multi-nginx
  - docker push atdinhnhan/multi-server
  - docker push atdinhnhan/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: ap-southeast-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-ap-southeast-1-805444218240
  bucket_path: multi-docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

language: generic